[package]
name = "cameronpcampbell/rsml"
description="A language for Roblox's styling system."
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors=[ "Cameron Campbell" ]
exclude=[ "**" ]
include=[ "src", "src/**", "default.project.json", "wally.toml", "wally.lock", "default.project.json", "LICENSE.md" ]